# NLP - Bag of Words

1. Berdasarkan dataset Restaurant_Reviews.tsv yang sudah dibahas sebelumnya (ada di WAG Cherno). Buatlah model Bag of Words dengan semua model klasifikasi yang ada (termasuk Naive Bayes yang sudah dikerjakan), dan carilah model dengan tingkat akurasi paling tinggi.

Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [ ]:
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter='\t', quoting=3)
dataset

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

Creating the Bag of Words model

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X.shape

(1000, 1500)

In [ ]:
y = dataset.iloc[:, -1].values
y.shape

(1000,)

Splitting the dataset into training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
X_test.shape

(200, 1500)

Training the Naive Bayes model on the training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

Predicting test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]

Making the Confusion Matrix and Accuracy Score

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[55 42]
 [12 91]]


In [ ]:
accuracy_score(y_test, y_pred)

0.73

Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred_lr = lr.predict(X_test)

KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn = knn.predict(X_test)

Linear(kernel) SVM

In [ ]:
from sklearn.svm import SVC
linear_svm = SVC(kernel = 'linear')
linear_svm.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
y_pred_svm = linear_svm.predict(X_test)


linear svm

In [ ]:
from sklearn.svm import SVC
classifier_kernel_svm = SVC(kernel = 'rbf', random_state = 0)
classifier_kernel_svm.fit(X_train, y_train)
y_pred_kernel_svm = classifier_kernel_svm.predict(X_test)

Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier_decision_tree = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier_decision_tree.fit(X_train, y_train)
y_pred_decision_tree = classifier_decision_tree.predict(X_test)

Random Forest


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_random_forest= RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier_random_forest.fit(X_train, y_train)
y_pred_random_forest = classifier_random_forest.predict(X_test)

Accuracy Score

In [ ]:
# logistic regression
accuracy_score(y_test, y_pred_lr)

0.775

In [ ]:
# K-NN
accuracy_score(y_test, y_pred_knn)


0.645

In [ ]:
# Linear SVM(Winner!!!)
accuracy_score(y_test, y_pred_svm)

0.79

In [ ]:
# Kernel SVM
accuracy_score(y_test, y_pred_kernel_svm)


0.78

In [ ]:
# Linear decission tree
accuracy_score(y_test, y_pred_decision_tree)


0.75

In [ ]:
# Linear random forest
accuracy_score(y_test, y_pred_random_forest)

0.725

2. Coba tingkatkan lagi akurasinya dengan menyesuaikan daftar stopwords yang digunakan (seperti me-remove “not” dari daftar stopwords). Berapa tingkat akurasi tertinggi yang bisa dicapai?

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter='\t', quoting=3)
dataset

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

## Cleaning the text

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
# list text yg sudah di-cleaning
corpus = []
for i in range(0, 1000):
    # ubah semua text selain a-z A-Z menjadi spasi kosong
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i]) # string
    review = review.lower() # string
    review = review.split() # list
    # stemming: ubah kata ke bentuk dasarnya
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)] # list
    review = ' '.join(review) # string
    corpus.append(review)
print(corpus)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price', 'get angri want damn pho', 'honeslti tast fresh', 'potato like rubber could tell made ahead time kept warmer', 'fri great', 'great touch', 'servic prompt', 'would not go back', 'cashier care ever say still end wayyy overpr', 'tri cape cod ravoli chicken cranberri mmmm', 'disgust pretti sure human hair', 'shock sign indic cash', 'highli recommend', 'waitress littl slow servic', 'place not worth time let alon vega', 'not like', 'burritto blah', 'food amaz', 'servic also cute', 'could care less interior beauti', 'perform', 'right red velvet cake ohhh stuff good', 'never brought salad ask', 'hole wall great mexican street taco friendli staff', 'took hour get food tabl restaur food luke warm sever run around like total overwhelm', 'worst salmon sashimi', 'also combo like burger fri beer decent deal', 'like final blow', 'found place accid could not

In [ ]:
len(corpus)

1000

## Creating the Bag of Words model

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X.shape

(1000, 1500)

In [ ]:
y = dataset.iloc[:, -1].values
y.shape

(1000,)

## Splitting the dataset into training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
X_test.shape

(200, 1500)

## Training the Naive Bayes model on the training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Predicting test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]

## Making the Confusion Matrix and Accuracy Score

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[55 42]
 [12 91]]


In [ ]:
accuracy_score(y_test, y_pred)

0.73

## Predicting single text value

In [ ]:
new_review = 'I really hate this restaurant so much'
 # ubah semua text selain a-z A-Z menjadi spasi kosong
new_review = re.sub('[^a-zA-Z]', ' ', new_review) # string
new_review = new_review.lower() # string
new_review = new_review.split() # list
# stemming: ubah kata ke bentuk dasarnya
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)] # list
new_review = ' '.join(new_review) # string
new_corpus = [new_review]
new_X_test = cv.transform(new_corpus).toarray()
new_y_pred = classifier.predict(new_X_test)
print(new_y_pred)

[0]


Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred_lr = lr.predict(X_test)

K-NN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn = knn.predict(X_test)

Linear(kernel) SVM

In [ ]:
from sklearn.svm import SVC
linear_svm = SVC(kernel = 'linear')
linear_svm.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
y_pred_svm = linear_svm.predict(X_test)

Linear SVM

In [ ]:
from sklearn.svm import SVC
classifier_kernel_svm = SVC(kernel = 'rbf', random_state = 0)
classifier_kernel_svm.fit(X_train, y_train)
y_pred_kernel_svm = classifier_kernel_svm.predict(X_test)

Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier_decision_tree = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier_decision_tree.fit(X_train, y_train)
y_pred_decision_tree = classifier_decision_tree.predict(X_test)

Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_random_forest= RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier_random_forest.fit(X_train, y_train)
y_pred_random_forest = classifier_random_forest.predict(X_test)

Accuracy Score

In [ ]:
# logistic regression
accuracy_score(y_test, y_pred_lr)

0.775

In [ ]:
# K-NN
accuracy_score(y_test, y_pred_knn)

0.645

In [ ]:
# Linear SVM (Winner!!!!)
accuracy_score(y_test, y_pred_svm)

0.79

In [ ]:
# Kernel SVM
accuracy_score(y_test, y_pred_kernel_svm)

0.78

In [ ]:
# Linear decission tree
accuracy_score(y_test, y_pred_decision_tree)

0.75

In [ ]:
# Linear random forest
accuracy_score(y_test, y_pred_random_forest)

0.725

3. Menurut Anda apa saja yang perlu diubah/ditambah jika Anda diminta melakukan sentimen analisis menggunakan Bahasa Indonesia?

3. Menurut Anda apa saja yang perlu diubah/ditambah jika Anda diminta melakukan sentimen analisis menggunakan Bahasa Indonesia?


Untuk Melakukan Sentimen Analisis ada beberapa hal yang perlu diubah/ditambah yaitu :
1. Kita perlu melakukan Case folding pada data yang kita punya, contoh nya seperti mengubah teks menjadi lower case(huruf kecil) , menghapus Url, Karakter tanda baca, dan menghapus angka pada dataset.
2. Kita perlu melakukan Word Normalization, untuk mengubah kata kata yang tidak baku pada dataset menjadi kata baku.
3. Kita perlu melakukan Filttering (Stopword Removal), yaitu mempersingkat kata(menghapus kata kata pada dataset yang kurang penting).
4. Membuat model klasifikasi untuk prediksi.